//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VismutaGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VismutaGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string frmMain_About {
            get {
                return ResourceManager.GetString("frmMain_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: Copy, RUN POWERSHELL AS ADMIN, Right-Click PS.
        /// </summary>
        internal static string frmMain_AdminUsage {
            get {
                return ResourceManager.GetString("frmMain_AdminUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the source files could not be found.
        /// </summary>
        internal static string frmMain_AnySourceFileNotFound {
            get {
                return ResourceManager.GetString("frmMain_AnySourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string frmMain_CopyToClipboard {
            get {
                return ResourceManager.GetString("frmMain_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt payload (Interactive).
        /// </summary>
        internal static string frmMain_EncryptPayloadInteractive {
            get {
                return ResourceManager.GetString("frmMain_EncryptPayloadInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt payload (Non-Interactive).
        /// </summary>
        internal static string frmMain_EncryptPayloadNonInteractive {
            get {
                return ResourceManager.GetString("frmMain_EncryptPayloadNonInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception when trying to read source file.
        /// </summary>
        internal static string frmMain_ExceptionWhenReadingSourceFile {
            get {
                return ResourceManager.GetString("frmMain_ExceptionWhenReadingSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception when trying to read/zip source files.
        /// </summary>
        internal static string frmMain_ExceptionWhenZippingSourcesFiles {
            get {
                return ResourceManager.GetString("frmMain_ExceptionWhenZippingSourcesFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute as SYSTEM (implies run after deploy).
        /// </summary>
        internal static string frmMain_ExecuteAsSystem {
            get {
                return ResourceManager.GetString("frmMain_ExecuteAsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PowerShell.
        /// </summary>
        internal static string frmMain_GeneratePowerShell {
            get {
                return ResourceManager.GetString("frmMain_GeneratePowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon by DeviantDark used under LGPL.
        /// </summary>
        internal static string frmMain_IconLicense {
            get {
                return ResourceManager.GetString("frmMain_IconLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyphrase.
        /// </summary>
        internal static string frmMain_Keyphrase {
            get {
                return ResourceManager.GetString("frmMain_Keyphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sources selected.
        /// </summary>
        internal static string frmMain_MultipleSourcesSelected {
            get {
                return ResourceManager.GetString("frmMain_MultipleSourcesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obfuscate payload name.
        /// </summary>
        internal static string frmMain_ObfuscatePayloadName {
            get {
                return ResourceManager.GetString("frmMain_ObfuscatePayloadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obfuscate PowerShell variables.
        /// </summary>
        internal static string frmMain_ObfuscateVariables {
            get {
                return ResourceManager.GetString("frmMain_ObfuscateVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string frmMain_OutputLabel {
            get {
                return ResourceManager.GetString("frmMain_OutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload arguments.
        /// </summary>
        internal static string frmMain_PayloadArguments {
            get {
                return ResourceManager.GetString("frmMain_PayloadArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload file(s).
        /// </summary>
        internal static string frmMain_PayloadFiles {
            get {
                return ResourceManager.GetString("frmMain_PayloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run after deploy.
        /// </summary>
        internal static string frmMain_RunAfterDeploy {
            get {
                return ResourceManager.GetString("frmMain_RunAfterDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy and run this FIRST, then either copy or type the keyphrase (Typing is more secure!).
        /// </summary>
        internal static string frmMain_RunFirstLabel {
            get {
                return ResourceManager.GetString("frmMain_RunFirstLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file could not be found.
        /// </summary>
        internal static string frmMain_SourceFileNotFound {
            get {
                return ResourceManager.GetString("frmMain_SourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: Copy, Run PowerShell, Right-Click PS.
        /// </summary>
        internal static string frmMain_StandardUsage {
            get {
                return ResourceManager.GetString("frmMain_StandardUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use memory injection (precludes most other options).
        /// </summary>
        internal static string frmMain_UseInjection {
            get {
                return ResourceManager.GetString("frmMain_UseInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vismutaicon {
            get {
                object obj = ResourceManager.GetObject("vismutaicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
